---
-
  hosts: test-routers
  gather_facts: false
  connection: local
  vars_files:
    - secrets.yaml

  tasks:
    - name: Create new user
      iosxr_config:
        lines:
          - group root-lr
          - secret {{ password }}
        parents: username {{ newuser }}
        provider: "{{ credentials }}"
        backup: yes
      register: result
    - debug: var=result