---
-
  hosts: test-routers
  gather_facts: false
  connection: local
  vars_files:
    - secrets.yaml

  tasks:
    - name: High-level system settings
      iosxr_system:
        name_servers:
          - 208.67.222.222
          - 208.67.220.220
        provider: "{{ credentials }}"
      register: result
    - debug: var=result
