---
-
  hosts: test-routers
  gather_facts: false
  connection: local
  vars_files:
    - secrets.yaml

  tasks:
    - name: OSPF process 2
      ydkOspfModule:
        process: 2
        state: absent
        router-id: 1.1.1.1
        areas: "{{ ospf_cfg['areas'] }}"
        provider: "{{ ydk }}"
      register: result
    - debug: var=result
